// ============================================================
// WORD DATA
// ============================================================

// WORDLE WORD LISTS
// -----------------
// Two lists: "answers" (words that can be the secret word) and
// "valid" (additional words the player can type as guesses).
// Keeping them separate means the answer is always a common,
// well-known word, while we still accept obscure guesses.

const WORDLE_ANSWERS = [
  'about','above','abuse','actor','acute','admit','adopt','adult','after','again',
  'agent','agree','ahead','alarm','album','alert','alien','align','alive','alley',
  'allow','alone','along','alter','among','angel','anger','angle','angry','anime',
  'ankle','apart','apple','apply','arena','argue','arise','armor','array','arrow',
  'aside','asset','atlas','avoid','awake','award','aware','badly','baker','basic',
  'basin','basis','batch','beach','beard','beast','begin','being','below','bench',
  'bible','birth','black','blade','blame','blank','blast','blaze','bleed','blend',
  'bless','blind','block','blood','bloom','blown','board','bonus','booth','bound',
  'brain','brand','brave','bread','break','breed','brick','bride','brief','bring',
  'broad','broke','brook','brown','brush','buddy','build','built','bunch','burst',
  'buyer','cabin','cable','camel','candy','cargo','carry','catch','cause','chain',
  'chair','chaos','charm','chart','chase','cheap','check','cheek','cheer','chess',
  'chest','chief','child','china','choir','chunk','civil','claim','clash','class',
  'clean','clear','clerk','click','cliff','climb','cling','clock','clone','close',
  'cloud','coach','coast','color','comet','comic','coral','couch','could','count',
  'court','cover','crack','craft','crane','crash','crazy','cream','crime','crown',
  'cruel','crush','curve','cycle','daily','dance','datum','dealt','decay','debut',
  'delay','dense','depth','derby','devil','dirty','donor','doubt','dough','draft',
  'drain','drama','drank','drawn','dream','dress','drift','drill','drink','drive',
  'drown','dying','eager','early','earth','eight','elect','elite','email','empty',
  'enemy','enjoy','enter','entry','equal','error','essay','event','every','exact',
  'exile','exist','extra','faint','faith','false','fancy','fatal','fault','feast',
  'fence','fever','fiber','field','fifth','fifty','fight','final','first','flame',
  'flash','fleet','flesh','float','flood','floor','flora','flour','fluid','flush',
  'focus','force','forge','forth','forum','found','frame','frank','fraud','fresh',
  'front','fruit','fully','funny','genre','ghost','giant','given','glass','globe',
  'gloom','glory','glove','grace','grade','grain','grand','grant','grape','grasp',
  'grass','grave','great','green','greet','grief','grill','grind','groan','gross',
  'group','grove','grown','guard','guess','guide','guilt','happy','harsh',
  'haven','heart','heavy','hence','herbs','hobby','honey','honor','horse',
  'hotel','house','human','humor','hurry','ideal','image','imply','index','indie',
  'inner','input','irony','ivory','jewel','joint','joker','judge','juice','juicy',
  'knife','knock','known','label','labor','large','laser','later','laugh','layer',
  'learn','least','leave','legal','lemon','level','light','limit','linen','liver',
  'local','lodge','logic','login','loose','lover','lower','loyal','lucky','lunch',
  'magic','major','maker','manor','maple','march','marry','match','mayor','media',
  'mercy','merit','metal','meter','midst','might','minor','minus','mixed',
  'model','money','month','moral','motor','mount','mouse','mouth','movie','music',
  'naked','nerve','never','night','noble','noise','north','noted','novel','nurse',
  'nylon','occur','ocean','offer','olive','onset','opera','orbit','order','organ',
  'other','outer','owner','oxide','ozone','paint','panel','panic','patch',
  'pause','peace','peach','pearl','penny','phase','phone','photo','piano','piece',
  'pilot','pitch','pixel','pizza','place','plain','plane','plant','plate','plaza',
  'plead','pluck','point','polar','pound','power','press','price','pride','prime',
  'print','prior','prize','probe','prone','proof','prose','proud','prove',
  'pulse','punch','pupil','queen','query','quest','queue','quick','quiet','quota',
  'quote','radar','radio','raise','rally','range','rapid','ratio','reach','react',
  'realm','rebel','refer','reign','relax','reply','rider','ridge','rifle','right',
  'rigid','rival','river','robot','rocky','roman','rouge','rough','round','route',
  'royal','rugby','ruler','rural','saint','salad','sauce','scale','scare','scene',
  'scope','score','sense','serve','seven','shade','shaft','shake','shall','shame',
  'shape','share','shark','sharp','sheep','sheer','sheet','shelf','shell','shift',
  'shirt','shock','shore','short','shout','sight','since','sixth','sixty','sized',
  'skill','skull','slash','slave','sleep','slice','slide','slope','smart','smell',
  'smile','smoke','snake','solar','solid','solve','sorry','sound','south','space',
  'spare','spark','speak','speed','spend','spice','spine','spite','split','spoke',
  'spoon','sport','spray','squad','stack','staff','stage','stain','stake','stale',
  'stall','stamp','stand','stare','stark','start','state','stays','steal','steam',
  'steel','steep','steer','stick','stiff','still','stock','stone','stood','store',
  'storm','story','stove','stuff','style','sugar','suite','sunny','super','surge',
  'swamp','swear','sweep','sweet','swept','swift','swing','sword','swore','sworn',
  'syrup','table','taste','teach','teeth','thank','theme','there','thick','thing',
  'think','third','thorn','those','three','threw','throw','thumb','tiger','tight',
  'timer','tired','title','toast','today','token','tooth','topic','total','touch',
  'tough','towel','tower','toxic','trace','track','trade','trail','train','trait',
  'trash','treat','trend','trial','tribe','trick','tried','troop','truck','truly',
  'trump','trunk','trust','truth','tumor','twice','twist','ultra','uncle','under',
  'union','unite','unity','until','upper','upset','urban','usage','usual','utter',
  'valid','value','valve','vault','venue','verse','video','vigor','vinyl','virus',
  'visit','vital','vivid','vocal','voice','voter','wagon','waste','watch','water',
  'weary','weave','wedge','weigh','weird','wheat','wheel','where','which','while',
  'white','whole','whose','widow','width','witch','woman','woods','world','worry',
  'worst','worth','would','wound','wrist','write','wrong','wrote','yacht','young',
  'youth','zebra'
];

// Additional valid guesses (player can type these, but they won't be chosen as answers)
// This list is intentionally very large to accept as many real English words as possible.
// It includes plurals of 4-letter words, verb forms, and less common vocabulary.
const WORDLE_VALID_GUESSES = new Set([
  ...WORDLE_ANSWERS,

  // ---- Plurals of common 4-letter words (adding 's' to make 5 letters) ----
  'babes','backs','baits','bakes','bales','balls','bands',
  'banes','bangs','banks','barks','barns','bases','baths','bawls',
  'beads','beaks','beams','beans','bears','beats','becks','beefs',
  'beers','bells','belts','bends','bents','bergs','bests','bikes','bills',
  'binds','birds','bites','blobs','blots','blows','blues','blurs','boars',
  'boats','bocks','bodes','boils','bolts','bombs','bonds','bones',
  'books','booms','boons','boots','bores','bosss','bouts','bowls','brags',
  'brans','brews','brigs','brims','brins','brows','bucks','buffs',
  'bulbs','bulks','bulls','bumps','bunks','bunns','burns','burrs','busts',
  'butts','bytes','cafes','cages','cakes','calls','calms','camps',
  'canes','capes','cards','cares','carps','carts','cases','casks','casts',
  'caves','cells','cents','chars','chats','chefs','chins','chips','chops',
  'chows','cites','clads','clams','clans','claps','claws','clays','clips',
  'clods','clogs','clots','clubs','clues','coals','coats','cocks','codes',
  'coils','coins','cokes','colts','combs','cones','cooks','cools','copes',
  'cords','cores','corks','corns','costs','coups','coves','crabs','crams',
  'crews','crops','crows','cubes','cuffs','cults','curbs','curds','cures',
  'curls','dales','dames','damns','damps','dares','darns','darts','dates',
  'dawns','deals','deans','decks','deeds','deems','deeps','demos','dials',
  'dices','diets','dimes','dines','discs','docks','doles','dolls','domes',
  'dooms','doors','doses','dotes','doves','downs','drabs','drags','drips',
  'drops','drums','dryss','duals','ducks','dudes','duels','duets','dukes',
  'dulls','dumps','dunes','dunks','dupes','dusts','earls','earns','eases',
  'easts','eaves','edits','elves','emits','epics','exams',
  'faces','facts','fades','fails','fairs','fakes','falls','fames','fangs',
  'fares','farms','fasts','fates','fawns','fazes','fears','feats','feeds',
  'feels','fells','felts','fends','ferns','fests','feuds','files','fills',
  'films','finds','fines','fires','firms','fists','fives','flags','flaks',
  'flans','flaps','flats','flaws','fleas','flips','flits','flogs','flops',
  'flows','flubs','flues','foams','foils','folds','folks','fonts','foods',
  'fools','fords','forks','forms','forts','fouls','fours','fowls','foxes',
  'frays','frets','frogs','fuels','fumes','funds','funks','fuses',
  'gages','gains','gaits','gales','galls','games','gangs','gapes','garbs',
  'gasps','gates','gawks','gazes','gears','genes','gifts','gilds','gilts',
  'gists','gives','glads','glams','glens','glows','glues','gluts','gnats',
  'gnaws','goads','goals','goats','golds','golfs','gongs','goods','gores',
  'gouge','grabs','grams','grays','greys','grids','grins','grips','grits',
  'groan','grubs','gulfs','gulls','gulps','gunks','gusts',
  'hacks','hails','hairs','hales','halls','halts','hands','hangs','hanks',
  'hares','harms','harps','hasps','hates','hauls','hawks','hazes','heads',
  'heals','heaps','hears','heats','heeds','heels','heirs','helms','helps',
  'herbs','herds','heros','hicks','hides','hikes','hills','hilts','hinds',
  'hints','hires','hives','hoaks','hobos','hocks','holds','holes','homes',
  'hoods','hoofs','hooks','hoops','hopes','horns','hoses','hosts','hours',
  'howls','huffs','hulks','hulls','humps','hunks','hunts','hurls','husks',
  'hymns','hypes','icons','ideas','idols','items','jacks','jades','jails',
  'jeans','jeeps','jeers','jells','jerks','jests','jibes','jilts','jives',
  'jocks','joins','jokes','jolts','jowls','jumps','junks','keels','keeps',
  'kicks','kills','kilns','kilts','kinds','kings','kinks','kites','knees',
  'knits','knobs','knots','knows','laces','lacks','lakes','lambs','lamps',
  'lands','lanes','larks','lauds','lavas','lawns','leads','leafs','leaks',
  'leaps','leers','lends','licks','lieds','liens','lifes','lifts','likes',
  'limbs','limes','limps','lines','links','lions','lisps','lists','lives',
  'loads','loafs','loams','loans','lobes','locks','lodes','lofts','loins',
  'looks','looms','loops','loots','lords','loses','loves','lucks','luges',
  'lumps','lures','lurks','lusts','lutes','lyres','maces','maids','mails',
  'mains','makes','males','malls','malts','manes','mares','marks','masks',
  'masts','mates','mauls','mazes','meads','meals','means','meats','meeks',
  'meets','melds','melts','memos','mends','menus','meows','meshs','micks',
  'miles','milks','mills','mimes','minds','mines','mints','mires','mists',
  'mites','mitts','moans','moats','mocks','modes','molds','moles','molts',
  'monks','moods','moons','moors','moots','mopes','morns','moths','moves',
  'mucks','muffs','mules','mulls','mumps','muses','musks','myths',
  'nails','names','napes','naves','necks','needs','nests','nicks','nines',
  'nodes','nooks','noons','norms','noses','notes','nouns','nulls','oaths',
  'ogles','omens','omits','opens','opals','orcas','ovens','overs',
  'paces','packs','pacts','pages','pails','pains','pairs','pales',
  'palms','panes','pangs','pants','pares','parks','parts','paths','paves',
  'pawns','peaks','peals','pears','pecks','peels','peeps','peers','pelts',
  'pends','perks','perms','pests','picks','piers','pikes','piles',
  'pills','pines','pings','pinks','pints','pipes','plans','plays','pleas',
  'plods','plots','plows','ploys','plugs','plums','plops','plows','pocks',
  'poems','poets','pokes','poles','polls','pomps','ponds','pools','popes',
  'pores','porks','ports','poses','posts','pours','pouts','prays','preps',
  'preys','prods','proms','props','prows','pucks','puffs','pulls','pulps',
  'pumps','punks','purrs','putts','quads','quays','races','racks','rafts',
  'rages','raids','rails','rains','rakes','ramps','ranks','rants','rasps',
  'rates','raves','razes','reads','reals','reams','reaps','rears','reeds',
  'reefs','reeks','reels','reins','rends','rents','rests','rides','riffs',
  'rifts','rills','rimes','rinds','rings','rinks','riots','rises','risks',
  'rites','roads','roams','roars','robes','rocks','roles','rolls','romps',
  'roofs','rooks','rooms','roots','ropes','roses','rotes','roves','ruffs',
  'ruins','rules','rumps','rungs','runts','ruses','rusts','sacks','safes',
  'sagas','sages','sails','sakes','sales','salts','sands','saves','scabs',
  'scams','scans','scars','seals','seams','sears','seats','sects','seeds',
  'seeks','seeps','seers','sells','sends','sheds','shims','shins',
  'ships','shoes','shops','shots','shows','shuns','sides','sifts','sighs',
  'signs','silks','sills','silos','silts','sings','sinks','sires','sites',
  'skews','skids','skims','skins','skips','skits','slabs','slags','slams',
  'slaps','slats','slaws','slays','sleds','slims','slips','slits','slobs',
  'slogs','slops','slots','slows','slugs','slums','slurs','snags','snaps',
  'snips','snobs','snots','snows','snubs','soaks','soaps','soars','socks',
  'sodas','sofas','soils','soles','songs','soots','sores','sorts','souls',
  'soups','spans','spars','spats','specs','spins','spits','spots','spuds',
  'spurs','stabs','stags','stars','stays','stems','steps','stews','stirs',
  'stops','stubs','studs','stuns','sucks','suits','sulks','swabs',
  'swans','swaps','swims','tacks','tails','takes','tales','talks',
  'tanks','tapes','tasks','taxed','teams','tears','techs','tells','temps',
  'tends','tents','terms','terns','tests','texts','thuds','thugs','ticks',
  'tides','tiers','tiles','tilts','times','tines','tings','toads',
  'toils','tolls','tombs','tomes','tones','tools','torts',
  'tours','touts','towns','traps','trays','trees','treks','trims','trios',
  'trips','trots','trues','tubes','tucks','tufts','tunas','tunes','turfs',
  'turns','tusks','twigs','twins','twits','types','typos',
  'units','urges','users','vales','vanes','vases','veals','veers','veils',
  'veins','vends','vents','verbs','vests','vials','vices','views','vines',
  'vibes','vises','volts','votes','vowed','wades','wafts',
  'wages','wails','waits','wakes','walks','walls','wands','wants','wards',
  'warns','warps','warts','wasps','waves','weans','wears','weeds','weeks',
  'wells','welts','wicks','wiles','wilts','wimps','winds','wines','wings',
  'winks','wipes','wires','wisps','wolfs','wombs','woods','wools',
  'words','works','worms','wraps','wrens','yawns','years','yells','yelps',
  'yokes','zones','zooms',
  // Additional common plurals and words
  'acids','balms','girls','flask','limos','lymph','ninja','quips','screw','synth',
  'tryst','utile',

  // ---- Extended 5-letter vocabulary ----
  'aahed','aalii','abaci','aback','abaft','abash','abate','abbey','abbot','abhor',
  'abide','abode','abort','abyss','acorn','acrid','actin','adage','added','adder',
  'addle','adept','admin','adobe','adore','adorn','aegis','afoot','afoul','affix',
  'agave','agate','agave','agile','aging','aglow','agony','aider','aired','aisle',
  'alarm','algae','alibi','allot','alloy','aloft','alpha','altar','amass','amaze',
  'amber','amble','amend','amine','amino','amiss','ample','amuse','angel',
  'angst','annex','annoy','antic','anvil','aorta','aphid','aping','apnea','appro',
  'apron','aptly','arbor','ardor','areal','argon','arise','aroma','arose','asked',
  'askew','atoll','atone','attic','audio','augur','aunty','avian','await','awash',
  'awful','awoke','axial','axiom','azure',
  'badge','bagel','baggy','baits','balks','balmy','banal','bands','bangs','banjo',
  'banks','bards','bared','bares','barge','barks','barns','baron','basal','based',
  'bases','basil','baste','baton','bayou','beads','beady','beaks','beams','beans',
  'bears','beats','beaus','beefy','beeps','began','beige','being','belay','belch',
  'belle','bells','belly','belts','berth','berry','beset','bevel','bible','bicep',
  'bikes','billy','bingo','biome','birch','birds','bites','bland','blare','blast',
  'bleat','blimp','blink','bliss','blitz','bloat','blobs','bloke','blond','bloke',
  'blown','blues','bluff','blunt','blurt','blush','bogus','boils','bolts','bombs',
  'bonds','bones','books','booms','boots','borax','bored','borne','bosom','bossy',
  'botch','bough','bowel','bowed','bower','bowls','boxer','brace','braid','brash',
  'brass','brawn','braze','bread','break','bride','brine','brink','briny','brisk',
  'brood','broom','broth','brows','budge','buffs','buggy','bulge','bulks','bulky',
  'bulls','bully','bumps','bumpy','bunks','bunny','burly','burns','burnt','burps',
  'burro','bylaw','bytes',
  'cabal','cache','caddy','cadet','cadge','cagey','cairn','caked','cakes','calls',
  'calms','calve','cameo','camps','caned','canes','canal','canon','caper','caped',
  'capes','cards','cared','carer','cares','cargo','carol','carps','carry','carts',
  'carve','cases','caste','caulk','caves','cedar','chafe','chaff','chalk','champ',
  'chant','chaps','chard','chars','chasm','cheap','cheat','chewy','chick','chide',
  'chili','chill','chimp','chips','chirp','chose','chump','chore','churn','chute',
  'cider','cigar','cinch','circa','cited','cites','civic','clack','clads','clamp',
  'clams','clang','clank','claps','clasp','claws','clays','cleat','cleft','clerk',
  'click','climb','cline','clink','clips','cloak','clods','clogs','clops','clots',
  'clove','clown','clubs','cluck','clued','clues','clump','clung','clunk','clung',
  'cobra','cocoa','coded','codes','coils','coins','cokes','colts','combs','comes',
  'comma','conch','condo','coned','cones','coops','coped','copes','cords','corer',
  'cores','corgi','corks','corns','corps','costs','coupe','coups','coven','covet',
  'cowed','cowls','coyly','crabs','crags','cramp','crams','crane',
  'crank','craps','crass','crate','crave','crawl','creak','credo','creed','creek',
  'creep','crept','crest','crews','cribs','crick','crier','crimp','crisp','croak',
  'crock','crook','crone','crony','crook','crops','cross','crowd','crows','crude',
  'cruet','crumb','crush','crust','crypt','cubed','cubes','cubic','cumin','curds',
  'cured','cures','curls','curly','curry','curse','curve','cutie',
  'daddy','daffy','daily','dairy','daisy','dally','dance','dandy','dared','dares',
  'darks','darts','dated','dates','datum','dauby','dawns','deals','dealt','death',
  'debit','debug','decal','decks','decor','decoy','decry','deeds','deity','delay',
  'delta','delve','demon','denim','dense','depot','detox','deuce','diary',
  'diced','dices','digit','dimly','dinar','dined','diner','dines','dingy','diode',
  'dirge','disco','ditch','ditty','ditto','dived','diver','dives','dizzy','dodge',
  'dodgy','doing','dolls','dolly','donor','donut','dooms','doors','doped','doper',
  'dopes','dorky','dorms','dosed','doses','dotty','doubt','dough','douse','dowdy',
  'dowel','downs','downy','doyen','dozed','dozen','dozes','drabs','drags','drake',
  'drank','drape','drape','drawn','draws','dread','dream','dried','drier','dries',
  'drift','drill','drink','drily','drips','drive','droit','droll','drone','drool',
  'droop','drops','dross','drove','drums','drunk','dryer','drily','dryly','ducal',
  'ducks','ducky','duels','duets','duffs','dulls','dully','dummy','dumps','dumpy',
  'dunes','dunks','dunce','duped','dupes','duple','dusty','dwarf','dwell','dwelt',
  'eager','eagle','eared','earls','early','earns','easel','eased','eater','eaten',
  'eater','eaves','ebbed','ebony','edged','edger','edges','edict','edits','eerie',
  'egret','eight','elbow','elder','elect','elfin','elite','elope','elude','elves',
  'email','embar','embed','ember','emcee','emoji','emote','enact','ended','endow',
  'enemy','enema','ensue','envoy','epoch','equip','erode','erred','erupt','essay',
  'ether','ethic','evade','evict','evoke','exalt','exams','excel','exert','exile',
  'expat','expel','exude','exult','eying',
  'fable','faced','facer','faces','facet','facts','faded','fades','fails','fairy',
  'faked','faker','fakes','falls','false','famed','fames','fancy','fangs','farce',
  'fared','fares','farms','fatal','fatly','fatty','fault','fauna','favor','feast',
  'feats','feeds','feels','feign','feint','fella','felon','femur','fence','fends',
  'ferns','ferry','fetal','fetch','fetid','fetus','feuds','fibre','fiend','fiery',
  'fifth','fifty','fight','filed','files','fills','films','filmy','filth','final',
  'finch','finds','fined','finer','fines','fired','fires','firms','first','fishy',
  'fists','fitly','fiver','fives','fixed','fixer','fixes','fizzy','fjord',
  'flack','flags','flail','flair','flake','flaky','flame','flank','flaps','flare',
  'flats','flaws','flaxy','fleas','fleck','flees','flesh','flick','flied','flier',
  'flies','fling','flint','flips','flirt','float','flock','flogs','flood','floor',
  'flops','floss','flour','flout','flown','flows','flubs','flues','fluff','fluid',
  'fluke','flung','flunk','flush','flute','foamy','focal','folds','foils','folks',
  'folly','fonts','foods','fools','foray','forge','forgo','forks','forms','forte',
  'forth','forts','forty','found','fouls','fours','fowls','foxed','foxes','foyer',
  'frail','frame','frank','fraud','frays','freak','freed','freer','fresh','friar',
  'fried','fries','frill','frisk','fritz','frizz','frock','frogs','front','frost',
  'froth','froze','fruit','frump','fugal','fully','fumed','fumes','funds','fungi',
  'funky','funny','furry','fused','fuses','fussy','fuzzy','gaffe',
  'gages','gaily','gains','gaits','gales','galls','games','gamma','gangs','gaped',
  'gapes','garbs','gases','gasps','gates','gauge','gaudy','gauze','gavel','gawks',
  'gawky','gazer','gazes','gears','geeks','geeky','genes','genie','genre','gents',
  'germs','ghost','giant','giddy','gifts','gilds','gills','gilts','girth','given',
  'gives','gizmo','glade','gland','glare','glass','glaze','gleam','glean','glide',
  'glint','gloat','globe','gloom','glory','gloss','glove','glows','glued','glues',
  'glyph','gnash','gnome','goads','goals','goats','godly','going','golem',
  'golfs','goner','gongs','goods','goofs','goofy','goose','gorge','gorse','gouge',
  'gourd','gowns','grabs','grace','grade','graft','grain','grams','grand','grant',
  'grape','graph','grasp','grass','grate','grave','gravy','grays','graze','great',
  'greed','greek','green','greet','greys','grief','grill','grime','grimy','grind',
  'grins','gripe','grips','grits','groan','groin','groom','grope','gross','group',
  'grove','growl','grown','grows','grubs','gruel','gruff','grump','grunt','guano',
  'guava','guide','guild','guile','guilt','guise','gulch','gulls','gulps','gummy',
  'gunky','gunny','guppy','gusto','gusty','gutsy','gypsy',
  'habit','hacks','hails','hairs','hairy','haiku','hales','halts','halve','hands',
  'handy','hangs','hanks','happy','harem','hares','harks','harms','harps','harry',
  'harsh','hasps','haste','hasty','hatch','hated','hater','hates','hauls','haunt',
  'haven','havoc','hawks','hazel','heads','heady','heals','heaps','heard','hears',
  'heart','heath','heats','heave','heavy','hedge','heeds','heels','hefty','heirs',
  'heist','helix','hello','helps','hence','henna','herbs','herds','heron','hewed',
  'hider','hides','highs','hiked','hiker','hikes','hills','hilly','hilts','hinds',
  'hinge','hints','hippo','hippy','hired','hires','hitch','hived','hives','hoard',
  'hoary','hobby','hobos','hoist','holds','holed','holes','holly','holms','homer',
  'homes','honey','hoods','hoofs','hooks','hoops','hoped','hopes','horde','horns',
  'horny','horsy','hosed','hoses','hosts','hotel','hound','hours','house','hover',
  'howdy','howls','hubby','huffy','hulks','hulky','human','humid','humps','humus',
  'hunch','hunks','hunky','hunts','hurls','hurry','husky','hyena','hymen','hymns',
  'hyped','hyper','hypes',
  'icier','icily','icing','icons','ideal','ideas','idled','idler','idles','idols',
  'igloo','image','imbue','impel','imply','incur','index','indie','inept','inert',
  'infer','ingot','inked','inlet','inner','input','intel','inter','intro','inure',
  'ionic','irate','irked','irony','isles','issue','items','ivory',
  'jacks','jaded','jails','jazzy','jeans','jeeps','jeers','jelly',
  'jerks','jerky','jests','jewel','jiffy','jimmy','jibed','jibes','jiffy','jiggs',
  'jilts','jimmy','jinks','jived','jives','joans','jocks','joins','joint','joked',
  'joker','jokes','jolly','jolts','joust','joyed','judge','juice','juicy','julep',
  'jumbo','jumps','jumpy','juror','juicy',
  'karma','kayak','kebab','keels','keens','keeps','keyed','khaki','kicks','kills',
  'kilns','kilts','kinds','kings','kinks','kinky','kiosk','kites','knack','knead',
  'kneed','kneel','knees','knelt','knelt','knife','knits','knobs','knock','knoll',
  'knots','known','knows','knurl','koala','kudos',
  'label','labor','laced','lacer','laces','lacks','laden','ladle','lager','lakes',
  'lambs','lamed','lamer','lamps','lance','lands','lanes','lapel','lapse','large',
  'larks','laser','latch','later','latex','lathe','latte','lauds','laugh','lavas',
  'lawns','layer','leads','leafy','leaks','leaky','leans','leant','leaps','leapt',
  'learn','lease','least','leave','ledge','leech','leeks','lefty','legal','leggy',
  'lemma','lemon','lemur','lends','level','lever','licks','lifts','light',
  'liked','liken','likes','lilac','limbo','limbs','limed','limes','limit','limps',
  'lined','linen','liner','lines','lingo','links','lions','lipid','lists','liter',
  'lithe','litho','litre','lived','liven','liver','lives','livid','llama','loads',
  'loafs','loams','loamy','loans','loath','lobby','lobes','locks','lodes','lofts',
  'lofty','logic','logos','loins','login','loner','longs','looks','looms','loony',
  'loops','loopy','loose','loots','lords','lorry','lotus','lousy','loved',
  'lover','loves','lowed','lower','lucks','lucky','lucid','lulls','lumps','lumpy',
  'lunar','lunch','lunge','lungs','lurch','lured','lures','lurks','lusty','lyric',
  'macho','macro','mafia','magic','magma','maids','mails','mains','maize','major',
  'maker','makes','males','malls','malts','mamas','mango','mania','manor','maple',
  'march','mares','marks','marsh','mason','match','mated','mates','maths','matte',
  'mauls','maxim','mealy','means','meant','meats','meaty','medal','media','melee',
  'melon','melts','memos','mends','menus','mercy','merge','merit','merry','messy',
  'metal','meter','metro','micro','midst','might','miked','mikes','miles','milks',
  'milky','mills','mimed','mimes','mimic','mince','minds','mined','miner','mines',
  'minor','mints','minty','minus','mired','mires','mirth','miser','misty','miter',
  'mitre','mixed','mixer','mixes','moans','moats','mocks','modal','model','modem',
  'modes','moist','molar','molds','moldy','moles','molts','mommy','money','monks',
  'month','moods','moody','moons','moose','moral','morel','morph','morse','mossy',
  'motel','moths','motif','motor','motto','mould','moult','mound','mount','mourn',
  'mouse','mousy','moved','mover','moves','movie','mowed','mower','mucus','muddy',
  'muffs','mulch','mules','mulls','mummy','mumps','mural','murky','mushy','music',
  'musks','musky','mussy','musty','muted','mutes','myrrh','myths',
  'nacho','nails','naive','named','names','nanny','napes','nappy','nasal','nasty',
  'naval','navel','neaps','nears','necks','needs','nerds','nerdy','nerve','nervy',
  'nests','newer','newly','nexus','nicer','niche','nicks','niece','nifty','night',
  'nimby','nines','ninny','nippy','nitty','noble','nobly','nodes','noise','noisy',
  'nomad','nonce','nooks','norms','notch','noted','notes','nouns','novae','novel',
  'nudge','nukes','nulls','numbs','nurse','nutty','nylon','nymph',
  'oaken','oared','oases','oasis','oater','oaths','occur','ocean','ochre','oddly',
  'offal','offer','often','ogled','ogler','ogles','oiled','oiler','oinks','older',
  'olive','omega','omits','onset','oohed','oozed','oozes','opens','opera','opted',
  'optic','orbit','organ','other','otter','ought','ounce','outdo','outed','outer',
  'outgo','ovary','ovate','ovens','overt','ovoid','owing','owned','owner','oxide',
  'ozone',
  'paced','pacer','paces','packs','paddy','pagan','paged','pager','pages','pails',
  'pains','paint','pairs','palms','palsy','panda','paned','panel','panes','pangs',
  'pansy','pants','papal','paper','parch','pared','pares','paris','parka','parks',
  'parry','parse','parts','party','pasta','paste','pasty','patch','patio','patsy',
  'patty','pause','paved','paver','paves','pawns','payee','payer','peace','peach',
  'peaks','peals','pears','peats','pecan','pedal','peeks','peels','peeps','peers',
  'peeve','penal','pence','pends','penny','peppy','perch','peril','perks','perky',
  'perms','pesky','pesto','pests','petal','peter','petty','phase','phone','photo',
  'piano','picks','picky','piece','piers','piety','piggy','piked','pikes',
  'piled','piles','pills','pilot','pinch','pined','pines','pings','pinko','pinks',
  'pinky','pinto','pints','pious','piped','piper','pipes','pipit','pitch','piths',
  'pithy','piton','pivot','pixel','pixie','pizza','place','plaid','plait','plane',
  'plank','plans','plant','plash','plate','plaza','plead','pleas','pleat','plied',
  'plier','plies','plods','plonk','plots','plows','ploys','pluck','plugs','plumb',
  'plume','plump','plums','plums','plunk','plush','poach','pocks',
  'poems','poets','point','poise','poked','poker','pokes','polar','poled','poles',
  'polka','polls','polyp','pomps','ponds','pooch','pools','poops','poppy','porch',
  'pored','pores','porks','porky','ports','posed','poser','poses','posit','posse',
  'posts','potty','pouch','pouty','power','prams','prank','prawn','prays','preed',
  'preen','press','preys','price','prick','pride','pried','prier','pries','prime',
  'primp','print','prion','prior','prism','privy','prize','probe','prods','progs',
  'promo','proms','prone','prong','proof','props','prose','proud','prove','prowl',
  'prows','proxy','prude','prune','pryer','psalm','psych','pubes','pucks','pudgy',
  'puffs','puffy','pulls','pulps','pulpy','pulse','pumps','punch','punks','punny',
  'pupil','puppy','puree','purer','purge','purrs','purse','pushy','putts','putty',
  'pygmy',
  'quack','quaff','quail','quake','qualm','quart','quasi','quash','queen','queer',
  'quell','query','queue','quick','quiet','quill','quilt','quirk','quite','quota',
  'quote','quoth',
  'rabbi','rabid','raced','racer','races','racks','radar','radii','radio','radon',
  'rafts','raged','rages','raids','rails','rains','rainy','raise','raked','raker',
  'rakes','rally','ramen','ramps','ranch','randy','range','rangy','ranks','rants',
  'rapid','rarer','rasps','raspy','rated','rates','ratio','raved','raven','raves',
  'rayon','razor','reach','react','reads','ready','realm','reals','reams','reaps',
  'rears','rebel','rebut','recap','reeds','reedy','reefs','reeks','reels','refer',
  'refit','regal','rehab','reign','reins','relax','relay','relit','renal','rends',
  'renew','rents','repay','repel','reply','repos','repro','rerun','resin','rests',
  'retry','revel','rider','ridge','rifle','rifts','rigid','rigor','riled','rills',
  'rimed','rimes','rinds','rings','rinks','rinse','riots','ripen','riper','risen',
  'riser','rises','risky','rites','ritzy','rival','riven','river','rivet','roads',
  'roams','roars','roast','robed','robes','robin','robot','rocks','rocky','rodeo',
  'rogue','roles','rolls','roman','romps','roods','roofs','rooks','rooms','roomy',
  'roost','roots','roped','roper','ropes','roses','rosin','rotor','rouge','rough',
  'round','rouse','route','roved','rover','roves','rowdy','rowed','rower','royal',
  'ruble','ruddy','ruder','ruffs','rugby','ruins','ruled','ruler','rules','rumba',
  'rummy','rumor','rumps','runes','rungs','rupee','rural','ruses','rushy','rusks',
  'rusty',
  'sable','sabot','sacks','sadly','safes','sages','saggy','saint','sails','sakes',
  'salad','sales','sally','salon','salsa','salts','salty','salve','salvo','sands',
  'sandy','saner','satin','satyr','sauce','saucy','sauna','saute','saved','saver',
  'saves','savor','savvy','scald','scale','scalp','scams','scant','scare','scarf',
  'scary','scene','scent','scoff','scold','scone','scoop','scoot','scope','score',
  'scorn','scout','scowl','scram','scrap','scrub','scrum','seals','seams','seats',
  'sedan','seeds','seedy','seeks','seems','seeps','seize','sense','sepia','serin',
  'setup','seven','sever','sewed','sewer','shack','shady','shaft','shags','shake',
  'shaky','shale','shame','shams','shape','shard','shark','sharp','shave','shawl',
  'shawl','shear','sheds','sheen','sheep','sheer','sheet','shelf','shell','shift',
  'shims','shine','shins','shiny','shire','shirt','shone','shook','shoos','shoot',
  'shops','shore','shorn','short','shots','shout','shove','shown','shows','showy',
  'shred','shrub','shrug','shuck','shunt','shuts','sided','sides','siege','sieve',
  'sifts','sighs','sight','sigma','signs','silks','silky','sills','silly','silts',
  'since','sinew','singe','sings','sinks','siren','siren','sites','sixth','sixty',
  'sized','sizes','skate','skeet','skein','skied','skier','skies','skill','skimp',
  'skims','skins','skips','skirt','skulk','skull','skunk','slabs','slack','slags',
  'slain','slams','slang','slant','slaps','slash','slate','slats','slave','slays',
  'sleds','sleek','sleep','sleet','slept','slick','slide','slime','slimy','sling',
  'slink','slips','slits','slobs','slogs','slope','slops','slosh','sloth','slots',
  'slows','slugs','slump','slums','slung','slunk','slurp','slurs','slush','slyly',
  'smack','small','smart','smash','smear','smell','smelt','smile','smirk','smite',
  'smith','smock','smoke','smoky','snack','snags','snail','snake','snaky','snaps',
  'snare','snarl','sneak','sneer','snide','sniff','snipe','snips','snobs','snoop',
  'snore','snort','snots','snout','snowy','snubs','snuck','snuff','snugs','soapy',
  'soars','sober','socks','sofas','softy','soggy','soils','solar','soled','soles',
  'solid','solos','solve','songs','sonic','sonly','sooty','soppy','sorts',
  'souls','soups','soupy','south','sowed','sower','space','spade','spaed','spank',
  'spans','spare','spark','spars','spasm','spawn','speak','spear','speck','specs',
  'speed','spell','spend','spent','spice','spicy','spied','spiel','spier','spies',
  'spike','spiky','spill','spine','spiny','spite','spits','splat','split','spoke',
  'spool','spoon','sport','spots','spout','spray','spree','sprig','sprit',
  'sprue','spuds','spunk','spurn','spurs','spurt','squad','squat','squid',
  'stabs','stack','staff','stage','stags','staid','stain','stair','stake','stale',
  'stalk','stall','stamp','stand','stank','stare','stark','stars','start','stash',
  'state','stave','stays','stead','steak','steal','steam','steel','steep','steer',
  'stems','steps','stern','stews','stick','stiff','still','sting','stink',
  'stint','stirs','stock','stoic','stoke','stole','stomp','stone','stony','stood',
  'stool','stoop','stops','store','stork','storm','story','stout','stove','stows',
  'strap','straw','stray','strip','strum','strut','stuck','studs','study','stuff',
  'stump','stung','stunk','stunt','style','suave','sugar','suite','suits','sulks',
  'sulky','sunny','super','surge','sushi','swabs','swamp','swank','swans','swaps',
  'swarm','swath','swats','swear','sweat','sweep','sweet','swell','swept','swift',
  'swill','swine','swing','swipe','swirl','swish','swoon','swoop','sword','swore',
  'sworn','swung','syrup',
  'tabby','table','taboo','tacit','tacks','tacky','taffy','tails','taint','taken',
  'taker','takes','tales','talks','tamed','tamer','tames','tangs','tangy','tanks',
  'tapir','tapes','tardy','tares','tarns','tarps','tarry','tarot','tasks','taste',
  'tasty','tater','taunt','taunt','tawny','taxed','taxes','teach','teams','tears',
  'teary','tease','techs','teddy','teems','teens','teeth','tells','tempo','temps',
  'tends','tenor','tense','tenth','tents','tepee','tepid','terms','terns','terra',
  'terse','tests','texts','their','theme','there','these','theta','thick','thief',
  'thigh','thing','think','third','thorn','those','three','threw','throw','thuds',
  'thugs','thumb','thump','tidal','tides','tiers','tiger','tight','tiled','tiles',
  'tilts','timed','timer','times','timid','tines','tinge','tipsy','tired','tires',
  'titan','title','toast','toddy','today','toffs','toils','token','tolls','tombs',
  'tomes','toned','toner','tones','tongs','tonic','tools','tooth','topaz','toped',
  'toper','topic','topps','torch','torso','torts','total','totem','toted','totem',
  'touch','tough','tours','towed','towel','tower','towns','toxic','trace','track',
  'tract','trade','trail','train','trait','tramp','trams','traps','trash','trawl',
  'trays','tread','treat','treed','trees','trend','tress','trial','tribe','trick',
  'tried','trier','tries','trigs','trims','trios','trips','trite','troll','tromp',
  'troop','trope','troth','trots','trout','trove','trowl','truce','truck',
  'trued','truer','trues','truly','trump','trunk','truss','trust','truth','tubes',
  'tucks','tufts','tulip','tumor','tunas','tuned','tuner','tunes','tunic','tuple',
  'turns','turfs','turfy','tusks','tutor','tutti','twang','tweak','tweed',
  'tweet','twice','twigs','twill','twine','twirl','twist','tying','tykes','typed',
  'types','typos',
  'udder','ulcer','ultra','umbra','umped','unbar','unbox','uncap','uncle','uncut',
  'under','undid','undue','unfed','unfit','unify','union','unite','unity','unlit',
  'unmet','unpin','unset','untie','until','unwed','unzip','upper','upset','urban',
  'urged','urges','usage','usher','using','usual','usurp','utter',
  'vague','valet','valid','valor','valve','vampy','vapid','vault',
  'vaunt','vegan','veils','veins','veiny','veldt','venal','vends','venom','vents',
  'venue','verbs','verge','verse','verve','vests','vexed','vibes','vicar','video',
  'views','vigor','villa','vines','vinyl','viola','viper','viral','visor','vista',
  'vital','vivid','vixen','vocal','vodka','vogue','voice','voila','vouch','vowed',
  'vowel','vying',
  'wacky','waded','wader','wades','wafer','waged','wager','wages','wagon','wails',
  'waist','waits','waked','waken','wakes','walks','walls','waltz','wands','waned',
  'wanes','wants','wards','wares','warns','warps','warts','warty','wasps','waste',
  'watch','water','waved','waver','waves','waxed','waxen','waxes','weals',
  'weans','wears','weary','weave','webby','wedge','wedgy','weeds','weedy','weeks',
  'weeps','weepy','weigh','weird','wells','welts','wench','whack','whale','whams',
  'wharf','wheat','wheel','where','which','whiff','while','whims','whine','whiny',
  'whips','whirl','whirs','whisk','white','whole','whoop','whose','wicks','widen',
  'wider','widow','width','wield','wifes','wilds','wiles','wills','wilts','wimps',
  'wimpy','wince','winch','winds','windy','wined','wines','wings','winks','wiped',
  'wiper','wipes','wired','wires','witch','witty','wives','wizen','woken','wolfs',
  'woman','women','wombs','woods','woody','wooed','wooer','woofs','wooly','woozy',
  'words','wordy','works','world','worms','wormy','worry','worse','worst','worth',
  'would','wound','woven','wrack','wraps','wrath','wreak','wreck','wrens','wring',
  'wrist','write','wrong','wrote','wryly',
  'xenon','xerox',
  'yacht','yanks','yards','yarns','yawns','yearn','years','yeast','yells','yelps',
  'yield','yolks','young','yours','youth','yowls',
  'zappy','zeals','zeros','zests','zesty','zincs','zings','zingy','zippy','zloty',
  'zonal','zoned','zones','zooms'
]);

// ============================================================
// CONNECTIONS PUZZLE DATA
// ============================================================
// Each puzzle has 4 groups. Each group has:
//   - name: the category
//   - words: the 4 words that belong to it
//   - difficulty: 0-3 (yellow, green, blue, purple)
//
// Difficulty determines the reveal color and hints at how
// tricky the connection is to find.

const CONNECTIONS_PUZZLES = [
  {
    id: 1,
    groups: [
      { name: 'Fruits', words: ['APPLE', 'MANGO', 'PEACH', 'GRAPE'], difficulty: 0 },
      { name: 'Card games', words: ['POKER', 'BRIDGE', 'HEARTS', 'SPADES'], difficulty: 1 },
      { name: 'Things that are round', words: ['GLOBE', 'WHEEL', 'CLOCK', 'PEARL'], difficulty: 2 },
      { name: '___ tree', words: ['PALM', 'FAMILY', 'DECISION', 'PINE'], difficulty: 3 }
    ]
  },
  {
    id: 2,
    groups: [
      { name: 'Kitchen utensils', words: ['WHISK', 'LADLE', 'TONGS', 'SPATULA'], difficulty: 0 },
      { name: 'Shades of blue', words: ['NAVY', 'AZURE', 'COBALT', 'TEAL'], difficulty: 1 },
      { name: 'Dance styles', words: ['WALTZ', 'SALSA', 'TANGO', 'SWING'], difficulty: 2 },
      { name: 'Double ___', words: ['DUTCH', 'AGENT', 'CHECK', 'VISION'], difficulty: 3 }
    ]
  },
  {
    id: 3,
    groups: [
      { name: 'Dog breeds', words: ['POODLE', 'BOXER', 'HUSKY', 'COLLIE'], difficulty: 0 },
      { name: 'Planets', words: ['VENUS', 'MARS', 'SATURN', 'PLUTO'], difficulty: 1 },
      { name: 'Music genres', words: ['JAZZ', 'BLUES', 'METAL', 'PUNK'], difficulty: 2 },
      { name: 'Also a fabric', words: ['SILK', 'DENIM', 'JERSEY', 'COTTON'], difficulty: 3 }
    ]
  },
  {
    id: 4,
    groups: [
      { name: 'Body parts', words: ['ELBOW', 'ANKLE', 'WRIST', 'KNEE'], difficulty: 0 },
      { name: 'Weather', words: ['THUNDER', 'BREEZE', 'FROST', 'HAIL'], difficulty: 1 },
      { name: 'Board games', words: ['CHESS', 'RISK', 'CLUE', 'SORRY'], difficulty: 2 },
      { name: 'Starts with a silent letter', words: ['KNIGHT', 'PSALM', 'GNOME', 'WRECK'], difficulty: 3 }
    ]
  },
  {
    id: 5,
    groups: [
      { name: 'Breakfast foods', words: ['WAFFLE', 'BAGEL', 'CEREAL', 'TOAST'], difficulty: 0 },
      { name: 'Ocean creatures', words: ['SHARK', 'SQUID', 'CORAL', 'WHALE'], difficulty: 1 },
      { name: 'Units of measurement', words: ['METER', 'POUND', 'GALLON', 'KELVIN'], difficulty: 2 },
      { name: 'Words before "house"', words: ['WARE', 'GREEN', 'FIRE', 'LIGHT'], difficulty: 3 }
    ]
  },
  {
    id: 6,
    groups: [
      { name: 'Vegetables', words: ['ONION', 'CARROT', 'PEPPER', 'CELERY'], difficulty: 0 },
      { name: 'Currencies', words: ['DOLLAR', 'FRANC', 'CROWN', 'POUND'], difficulty: 1 },
      { name: 'Types of jacket', words: ['BLAZER', 'PARKA', 'BOMBER', 'DENIM'], difficulty: 2 },
      { name: 'Words that follow "fire"', words: ['WORK', 'PLACE', 'TRUCK', 'FLY'], difficulty: 3 }
    ]
  },
  {
    id: 7,
    groups: [
      { name: 'Colors', words: ['SCARLET', 'AMBER', 'IVORY', 'VIOLET'], difficulty: 0 },
      { name: 'Gemstones', words: ['RUBY', 'OPAL', 'TOPAZ', 'PEARL'], difficulty: 1 },
      { name: 'Pasta shapes', words: ['PENNE', 'RIGATONI', 'FUSILLI', 'ORZO'], difficulty: 2 },
      { name: 'Also a name', words: ['GRACE', 'CHASE', 'HUNTER', 'BROOK'], difficulty: 3 }
    ]
  },
  {
    id: 8,
    groups: [
      { name: 'Footwear', words: ['SANDAL', 'BOOT', 'LOAFER', 'CLOG'], difficulty: 0 },
      { name: 'Parts of a book', words: ['SPINE', 'CHAPTER', 'INDEX', 'COVER'], difficulty: 1 },
      { name: 'Things with keys', words: ['PIANO', 'LAPTOP', 'LOCK', 'MAP'], difficulty: 2 },
      { name: 'Words after "back"', words: ['FIRE', 'BONE', 'TRACK', 'YARD'], difficulty: 3 }
    ]
  },
  {
    id: 9,
    groups: [
      { name: 'Steal', words: ['SWIPE', 'LIFT', 'PINCH', 'NICK'], difficulty: 0 },
      { name: 'Small amount', words: ['DASH', 'DROP', 'TOUCH', 'HINT'], difficulty: 1 },
      { name: '___ light', words: ['FLASH', 'LIME', 'HIGH', 'STOP'], difficulty: 2 },
      { name: 'Cocktails', words: ['GIMLET', 'SLING', 'JULEP', 'FIZZ'], difficulty: 3 }
    ]
  },
  {
    id: 10,
    groups: [
      { name: 'Trust as real', words: ['ACCEPT', 'BELIEVE', 'BUY', 'SWALLOW'], difficulty: 0 },
      { name: 'Power issues', words: ['OUTAGE', 'SHORT', 'SPIKE', 'SURGE'], difficulty: 1 },
      { name: 'Summary', words: ['ABSTRACT', 'BRIEF', 'DIGEST', 'OUTLINE'], difficulty: 2 },
      { name: 'Sounds like a first name', words: ['CURT', 'HAIRY', 'KNEEL', 'WANE'], difficulty: 3 }
    ]
  },
  {
    id: 11,
    groups: [
      { name: 'Old saying', words: ['ADAGE', 'CHESTNUT', 'MAXIM', 'SAW'], difficulty: 0 },
      { name: 'Fuel for grilling', words: ['CHARCOAL', 'ELECTRIC', 'GAS', 'WOOD'], difficulty: 1 },
      { name: 'Also a tree', words: ['ASH', 'CHERRY', 'EBONY', 'GUM'], difficulty: 2 },
      { name: 'Hot tub parts', words: ['FILTER', 'HEATER', 'JET', 'PUMP'], difficulty: 3 }
    ]
  },
  {
    id: 12,
    groups: [
      { name: 'Deplete', words: ['DRAIN', 'EMPTY', 'EXHAUST', 'SAP'], difficulty: 0 },
      { name: 'Play music with passion', words: ['GROOVE', 'JAM', 'ROCK', 'SHRED'], difficulty: 1 },
      { name: 'On a restaurant receipt', words: ['SIGNATURE', 'TAX', 'TIP', 'TOTAL'], difficulty: 2 },
      { name: 'Forms of sugar', words: ['CUBE', 'GRAIN', 'POWDER', 'SYRUP'], difficulty: 3 }
    ]
  },
  {
    id: 13,
    groups: [
      { name: 'Reward from hard work', words: ['FRUIT', 'RETURN', 'REWARD', 'YIELD'], difficulty: 0 },
      { name: 'Types of bagels', words: ['EGG', 'EVERYTHING', 'PLAIN', 'POPPY'], difficulty: 1 },
      { name: 'Contribute to a movie', words: ['ACT', 'DIRECT', 'PRODUCE', 'WRITE'], difficulty: 2 },
      { name: 'Start of a classic monster', words: ['FRANK', 'MUM', 'VAMP', 'WERE'], difficulty: 3 }
    ]
  },
  {
    id: 14,
    groups: [
      { name: 'Embodiment', words: ['EXAMPLE', 'IDEAL', 'MODEL', 'SYMBOL'], difficulty: 0 },
      { name: 'Related to trains', words: ['CAR', 'CONDUCTOR', 'STATION', 'TRACK'], difficulty: 1 },
      { name: 'Electric ___', words: ['CHAIR', 'EEL', 'FENCE', 'SLIDE'], difficulty: 2 },
      { name: 'Ear___', words: ['DRUM', 'MARK', 'WAX', 'WIG'], difficulty: 3 }
    ]
  },
  {
    id: 15,
    groups: [
      { name: 'Effortless', words: ['FLUID', 'GRACEFUL', 'NATURAL', 'SMOOTH'], difficulty: 0 },
      { name: 'Exertion', words: ['EFFORT', 'LABOR', 'SWEAT', 'WORK'], difficulty: 1 },
      { name: 'Energy for a device', words: ['BATTERY', 'CHARGE', 'JUICE', 'POWER'], difficulty: 2 },
      { name: 'What "pop" might mean', words: ['BURST', 'DAD', 'MAINSTREAM', 'SODA'], difficulty: 3 }
    ]
  },
  {
    id: 16,
    groups: [
      { name: 'Slang for head', words: ['COCONUT', 'CROWN', 'DOME', 'NOGGIN'], difficulty: 0 },
      { name: 'Palindromes', words: ['KAYAK', 'LEVEL', 'CIVIC', 'RADAR'], difficulty: 1 },
      { name: 'TV police procedurals', words: ['BONES', 'CASTLE', 'MONK', 'COLUMBO'], difficulty: 2 },
      { name: 'First in a comedy duo', words: ['ABBOTT', 'KEY', 'LAUREL', 'PENN'], difficulty: 3 }
    ]
  },
  {
    id: 17,
    groups: [
      { name: 'Yellow-brown shades', words: ['BEIGE', 'CAMEL', 'KHAKI', 'TAN'], difficulty: 0 },
      { name: 'Fail to attend', words: ['CUT', 'DITCH', 'MISS', 'SKIP'], difficulty: 1 },
      { name: 'Decisive victory', words: ['BLOWOUT', 'ROMP', 'ROUT', 'SWEEP'], difficulty: 2 },
      { name: '___ wheel', words: ['CHEESE', 'COLOR', 'HAMSTER', 'PRAYER'], difficulty: 3 }
    ]
  },
  {
    id: 18,
    groups: [
      { name: 'Sanctuary', words: ['HAVEN', 'PORT', 'RETREAT', 'SHELTER'], difficulty: 0 },
      { name: 'Football gear', words: ['CLEATS', 'HELMET', 'JERSEY', 'PADS'], difficulty: 1 },
      { name: 'Candy brands', words: ['CHARMS', 'KINDER', 'WONKA', 'YORK'], difficulty: 2 },
      { name: 'Free ___', words: ['BIRD', 'FALL', 'SOLO', 'WILLY'], difficulty: 3 }
    ]
  },
  {
    id: 19,
    groups: [
      { name: 'Herbs', words: ['BASIL', 'DILL', 'SAGE', 'THYME'], difficulty: 0 },
      { name: 'Poker terms', words: ['BLUFF', 'CALL', 'FOLD', 'RAISE'], difficulty: 1 },
      { name: 'Shades of red', words: ['BRICK', 'CRIMSON', 'MAROON', 'RUST'], difficulty: 2 },
      { name: '___ bar', words: ['CANDY', 'CROW', 'HANDLE', 'SPACE'], difficulty: 3 }
    ]
  },
  {
    id: 20,
    groups: [
      { name: 'Containers', words: ['BARREL', 'CHEST', 'CRATE', 'TRUNK'], difficulty: 0 },
      { name: 'Parts of a shoe', words: ['HEEL', 'LACE', 'SOLE', 'TONGUE'], difficulty: 1 },
      { name: 'Film festivals', words: ['CANNES', 'SUNDANCE', 'TRIBECA', 'VENICE'], difficulty: 2 },
      { name: '___stone', words: ['CORNER', 'GRIND', 'LIME', 'MILE'], difficulty: 3 }
    ]
  },
  {
    id: 21,
    groups: [
      { name: 'Enthusiast', words: ['BUFF', 'FAN', 'FIEND', 'NUT'], difficulty: 0 },
      { name: 'Also a bird', words: ['CRANE', 'MARTIN', 'ROBIN', 'SWIFT'], difficulty: 1 },
      { name: 'Capital cities', words: ['LIMA', 'OSLO', 'ROME', 'SOFIA'], difficulty: 2 },
      { name: '___work', words: ['CLOCK', 'DREAM', 'FOOT', 'FRAME'], difficulty: 3 }
    ]
  },
  {
    id: 22,
    groups: [
      { name: 'Quick look', words: ['GLANCE', 'GLIMPSE', 'PEEK', 'SCAN'], difficulty: 0 },
      { name: 'Ship parts', words: ['BOW', 'HULL', 'MAST', 'STERN'], difficulty: 1 },
      { name: 'Things with layers', words: ['CAKE', 'EARTH', 'LASAGNA', 'PARFAIT'], difficulty: 2 },
      { name: '___ out', words: ['BLACK', 'CHECK', 'FREAK', 'PHASE'], difficulty: 3 }
    ]
  },
  {
    id: 23,
    groups: [
      { name: 'Nonsense', words: ['BUNK', 'DRIVEL', 'HOGWASH', 'TRIPE'], difficulty: 0 },
      { name: 'Car parts', words: ['BUMPER', 'CLUTCH', 'FENDER', 'HOOD'], difficulty: 1 },
      { name: 'Types of cloud', words: ['CIRRUS', 'CUMULUS', 'NIMBUS', 'STRATUS'], difficulty: 2 },
      { name: '___mate', words: ['CHECK', 'CLASS', 'ROOM', 'SOUL'], difficulty: 3 }
    ]
  },
  {
    id: 24,
    groups: [
      { name: 'Things in a gym', words: ['BENCH', 'MAT', 'RACK', 'RING'], difficulty: 0 },
      { name: 'Textures', words: ['COARSE', 'ROUGH', 'SMOOTH', 'VELVET'], difficulty: 1 },
      { name: 'Famous pairs (one half)', words: ['CLYDE', 'GARFUNKEL', 'HARDY', 'ROBIN'], difficulty: 2 },
      { name: '___berry', words: ['BLACK', 'BLUE', 'GOOSE', 'STRAW'], difficulty: 3 }
    ]
  },
  {
    id: 25,
    groups: [
      { name: 'Abandon', words: ['DESERT', 'DITCH', 'DROP', 'DUMP'], difficulty: 0 },
      { name: 'Chess pieces', words: ['BISHOP', 'KING', 'KNIGHT', 'PAWN'], difficulty: 1 },
      { name: 'Mythical creatures', words: ['DRAGON', 'GRIFFIN', 'PHOENIX', 'UNICORN'], difficulty: 2 },
      { name: '___fish', words: ['CAT', 'JELLY', 'STAR', 'SWORD'], difficulty: 3 }
    ]
  },
  {
    id: 26,
    groups: [
      { name: 'Annoy', words: ['BUG', 'GRATE', 'IRK', 'NEEDLE'], difficulty: 0 },
      { name: 'Types of market', words: ['BEAR', 'BULL', 'FLEA', 'STOCK'], difficulty: 1 },
      { name: 'Awards', words: ['EMMY', 'GRAMMY', 'OSCAR', 'TONY'], difficulty: 2 },
      { name: '___board', words: ['CARD', 'CUP', 'DART', 'SKATE'], difficulty: 3 }
    ]
  },
  {
    id: 27,
    groups: [
      { name: 'Types of roll', words: ['DRUM', 'EGG', 'ROCK', 'SPRING'], difficulty: 0 },
      { name: 'Things in a wallet', words: ['CARD', 'CASH', 'PHOTO', 'RECEIPT'], difficulty: 1 },
      { name: 'Impressive', words: ['EPIC', 'GRAND', 'MIGHTY', 'STELLAR'], difficulty: 2 },
      { name: '___ house', words: ['DOLL', 'GREEN', 'PEN', 'POWER'], difficulty: 3 }
    ]
  },
  {
    id: 28,
    groups: [
      { name: 'Throw', words: ['CHUCK', 'HURL', 'PITCH', 'TOSS'], difficulty: 0 },
      { name: 'Parts of a river', words: ['BANK', 'BED', 'DELTA', 'MOUTH'], difficulty: 1 },
      { name: 'Space terms', words: ['COMET', 'METEOR', 'ORBIT', 'QUASAR'], difficulty: 2 },
      { name: '___land', words: ['FIN', 'ICE', 'IRE', 'NETHER'], difficulty: 3 }
    ]
  },
  {
    id: 29,
    groups: [
      { name: 'Catch', words: ['NAB', 'NET', 'SNAG', 'TRAP'], difficulty: 0 },
      { name: 'Math terms', words: ['FACTOR', 'MEDIAN', 'PRIME', 'ROOT'], difficulty: 1 },
      { name: 'James Bond actors', words: ['BROSNAN', 'CONNERY', 'CRAIG', 'MOORE'], difficulty: 2 },
      { name: '___line', words: ['DEAD', 'HEAD', 'PUNCH', 'TAG'], difficulty: 3 }
    ]
  },
  {
    id: 30,
    groups: [
      { name: 'Things that are pitched', words: ['BALL', 'IDEA', 'SONG', 'TENT'], difficulty: 0 },
      { name: 'Animal sounds', words: ['BARK', 'CHIRP', 'GROWL', 'HISS'], difficulty: 1 },
      { name: 'Paint types', words: ['ACRYLIC', 'ENAMEL', 'LATEX', 'MATTE'], difficulty: 2 },
      { name: '___cake', words: ['CUP', 'HOT', 'PAN', 'SHORT'], difficulty: 3 }
    ]
  }
];
